/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui.entidade;

import br.com.ies.oficina.dao.jdbc.JDBCFuncionarioDAO;
import br.com.ies.oficina.dao.jdbc.JDBCInventarioDAO;
import static br.com.ies.oficina.dominio.ManipuladorString.firstToUpperCase;
import br.com.ies.oficina.gui.alterar.AlterarFuncionario;
import br.com.ies.oficina.gui.alterar.AlterarPeca;
import br.com.ies.oficina.gui.cadastrar.CadastrarPeca;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Weeaboo
 */
public class EntidadeInventario extends javax.swing.JFrame {
    JDBCInventarioDAO JDBCInventario = new JDBCInventarioDAO();
    TableModel tableModel;
    
    public EntidadeInventario() {
        initComponents();
        tableModel = JDBCInventario.listarInventario();
        jTablePeca.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarNome = new javax.swing.JButton();
        jButtonBuscaMarca = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeca = new javax.swing.JTable();
        excluirPeca = new javax.swing.JLabel();
        editaPeca = new javax.swing.JLabel();
        adicionarPeca = new javax.swing.JLabel();
        atualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Inventario");

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButtonBuscarNome.setBackground(new java.awt.Color(46, 204, 113));
        jButtonBuscarNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jButtonBuscarNome.setForeground(new java.awt.Color(32, 33, 35));
        jButtonBuscarNome.setText("Buscar Nome");
        jButtonBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarNomeActionPerformed(evt);
            }
        });

        jButtonBuscaMarca.setBackground(new java.awt.Color(46, 204, 113));
        jButtonBuscaMarca.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jButtonBuscaMarca.setForeground(new java.awt.Color(32, 33, 35));
        jButtonBuscaMarca.setText("Buscar Marca");
        jButtonBuscaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaMarcaActionPerformed(evt);
            }
        });

        jTextFieldNome.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNome.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldMarca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldMarca.setForeground(new java.awt.Color(255, 255, 255));

        jTablePeca.setBackground(new java.awt.Color(32, 33, 35));
        jTablePeca.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jTablePeca.setForeground(new java.awt.Color(255, 255, 255));
        jTablePeca.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        jTablePeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePeca);

        excluirPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-lixo-30.png"))); // NOI18N
        excluirPeca.setToolTipText("Excluir Peça");
        excluirPeca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirPecaMouseClicked(evt);
            }
        });

        editaPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-editar-30.png"))); // NOI18N
        editaPeca.setToolTipText("Editar Peça");
        editaPeca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editaPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editaPecaMouseClicked(evt);
            }
        });

        adicionarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-30.png"))); // NOI18N
        adicionarPeca.setToolTipText("Nova Peça");
        adicionarPeca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adicionarPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarPecaMouseClicked(evt);
            }
        });

        atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-atualizações-disponíveis-30.png"))); // NOI18N
        atualizar.setToolTipText("Atualizar");
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionarPeca)
                        .addGap(18, 18, 18)
                        .addComponent(editaPeca)
                        .addGap(18, 18, 18)
                        .addComponent(excluirPeca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscaMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscarNome)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscaMarca)
                        .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atualizar))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirPeca)
                    .addComponent(editaPeca)
                    .addComponent(adicionarPeca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarNomeActionPerformed
        String nome = firstToUpperCase(jTextFieldNome.getText());
        tableModel = JDBCInventario.listarInventarioNome(nome);
        jTablePeca.setModel(tableModel);
    }//GEN-LAST:event_jButtonBuscarNomeActionPerformed

    private void jButtonBuscaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaMarcaActionPerformed
        String marca = firstToUpperCase(jTextFieldMarca.getText());
        tableModel = JDBCInventario.listarInventarioMarca(marca);
        jTablePeca.setModel(tableModel);
    }//GEN-LAST:event_jButtonBuscaMarcaActionPerformed

    private void adicionarPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarPecaMouseClicked
        new CadastrarPeca().setVisible(true);
    }//GEN-LAST:event_adicionarPecaMouseClicked

    private void editaPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editaPecaMouseClicked
        int rowSelected = jTablePeca.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma peça!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTablePeca.getModel();
            int cd_inventario = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            new AlterarPeca(cd_inventario).setVisible(true);
        }
    }//GEN-LAST:event_editaPecaMouseClicked

    private void excluirPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirPecaMouseClicked
        int rowSelected = jTablePeca.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma peça!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTablePeca.getModel();
            int cd_inventario = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            JDBCInventarioDAO JDBCInventario = new JDBCInventarioDAO();
            int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo deletar essa peça?");
            if(opcao == 0) {
                if(JDBCInventario.deletarInventario(cd_inventario)) {
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO ao deletar!!");
                }
            }
        }
    }//GEN-LAST:event_excluirPecaMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        tableModel = JDBCInventario.listarInventario();
        jTablePeca.setModel(tableModel);
    }//GEN-LAST:event_atualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntidadeInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntidadeInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntidadeInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntidadeInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntidadeInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionarPeca;
    private javax.swing.JLabel atualizar;
    private javax.swing.JLabel editaPeca;
    private javax.swing.JLabel excluirPeca;
    private javax.swing.JButton jButtonBuscaMarca;
    private javax.swing.JButton jButtonBuscarNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePeca;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
