/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui.entidade;

import br.com.ies.oficina.dao.jdbc.JDBCVeiculoDAO;
import br.com.ies.oficina.gui.alterar.AlterarFuncionario;
import br.com.ies.oficina.gui.alterar.AlterarVeiculo;
import br.com.ies.oficina.gui.cadastrar.CadastrarVeiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Weeaboo
 */
public class EntidadeVeiculo extends javax.swing.JFrame {
    JDBCVeiculoDAO JDBCVeiculo = new JDBCVeiculoDAO();
    TableModel tableModel;
    
    public EntidadeVeiculo() {
        initComponents();
        tableModel = JDBCVeiculo.listarVeiculo();
        jTableVeiculo.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarPlaca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        novoVeiculo = new javax.swing.JLabel();
        alterarVeiculo = new javax.swing.JLabel();
        excluirVeiculo = new javax.swing.JLabel();
        atualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Veiculo");

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButtonBuscarPlaca.setBackground(new java.awt.Color(46, 204, 113));
        jButtonBuscarPlaca.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jButtonBuscarPlaca.setForeground(new java.awt.Color(32, 33, 35));
        jButtonBuscarPlaca.setText("Buscar por Placa");
        jButtonBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPlacaActionPerformed(evt);
            }
        });

        jTableVeiculo.setBackground(new java.awt.Color(32, 33, 35));
        jTableVeiculo.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jTableVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jTableVeiculo.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVeiculo);

        jFormattedTextField2.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextField2.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        novoVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-30.png"))); // NOI18N
        novoVeiculo.setToolTipText("Novo Veiculo");
        novoVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoVeiculoMouseClicked(evt);
            }
        });

        alterarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-editar-30.png"))); // NOI18N
        alterarVeiculo.setToolTipText("Editar Veiculo");
        alterarVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alterarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarVeiculoMouseClicked(evt);
            }
        });

        excluirVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-lixo-30.png"))); // NOI18N
        excluirVeiculo.setToolTipText("Excluir Veiculo");
        excluirVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirVeiculoMouseClicked(evt);
            }
        });

        atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-atualizações-disponíveis-30.png"))); // NOI18N
        atualizar.setToolTipText("Atualizar");
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(novoVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(alterarVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(excluirVeiculo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(novoVeiculo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonBuscarPlaca)
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(atualizar))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alterarVeiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(excluirVeiculo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPlacaActionPerformed
        String placa = jFormattedTextField2.getText();
        tableModel = JDBCVeiculo.listarVeiculoPlaca(placa);
        jTableVeiculo.setModel(tableModel);
    }//GEN-LAST:event_jButtonBuscarPlacaActionPerformed

    private void novoVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoVeiculoMouseClicked
        new CadastrarVeiculo().setVisible(true);
    }//GEN-LAST:event_novoVeiculoMouseClicked

    private void alterarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarVeiculoMouseClicked
        int rowSelected = jTableVeiculo.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um veiculo!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableVeiculo.getModel();
            int cd_veiculo = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            new AlterarVeiculo(cd_veiculo).setVisible(true);
        }
    }//GEN-LAST:event_alterarVeiculoMouseClicked

    private void excluirVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirVeiculoMouseClicked
        int rowSelected = jTableVeiculo.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um veiculo!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableVeiculo.getModel();
            int cd_veiculo = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            JDBCVeiculoDAO JDBCVeiculo = new JDBCVeiculoDAO();
            int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo deletar esse veiculo?");
            if(opcao == 0) {
                if(JDBCVeiculo.deletarVeiculo(cd_veiculo)) {
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO ao deletar!!");
                }
            }
        }
    }//GEN-LAST:event_excluirVeiculoMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        tableModel = JDBCVeiculo.listarVeiculo();
        jTableVeiculo.setModel(tableModel);
    }//GEN-LAST:event_atualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntidadeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntidadeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntidadeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntidadeVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntidadeVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alterarVeiculo;
    private javax.swing.JLabel atualizar;
    private javax.swing.JLabel excluirVeiculo;
    private javax.swing.JButton jButtonBuscarPlaca;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JLabel novoVeiculo;
    // End of variables declaration//GEN-END:variables
}
