/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui.entidade;

import br.com.ies.oficina.dao.jdbc.JDBCClienteDAO;
import static br.com.ies.oficina.dominio.ManipuladorString.firstToUpperCase;
import br.com.ies.oficina.gui.alterar.AlterarCliente;
import br.com.ies.oficina.gui.cadastrar.CadastrarCliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Herik
 */
public class EntidadeCliente extends javax.swing.JFrame {
    JDBCClienteDAO JDBCCliente = new JDBCClienteDAO();
    TableModel tableModel;

    public EntidadeCliente() {
        initComponents();
        tableModel = JDBCCliente.listarCliente();
        jTableCliente.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarCliente = new javax.swing.JPanel();
        jButtonNome = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        novoCliente = new javax.swing.JLabel();
        buscaAvancada = new javax.swing.JLabel();
        editarCliente = new javax.swing.JLabel();
        deletarCliente = new javax.swing.JLabel();
        atulizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Cliente");
        setBackground(new java.awt.Color(32, 33, 35));

        jPanelBuscarCliente.setBackground(new java.awt.Color(32, 33, 35));

        jButtonNome.setBackground(new java.awt.Color(46, 204, 113));
        jButtonNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jButtonNome.setForeground(new java.awt.Color(32, 33, 35));
        jButtonNome.setText("Buscar por nome");
        jButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeActionPerformed(evt);
            }
        });

        jTextFieldNome.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNome.setForeground(new java.awt.Color(255, 255, 255));

        jTableCliente.setBackground(new java.awt.Color(32, 33, 35));
        jTableCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jTableCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTableCliente.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6"
            }
        ));
        jTableCliente.setOpaque(false);
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        novoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-usuário-masculino-30.png"))); // NOI18N
        novoCliente.setToolTipText("Novo Cliente");
        novoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoClienteMouseClicked(evt);
            }
        });

        buscaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-procurar-usuário-masculino-30.png"))); // NOI18N
        buscaAvancada.setToolTipText("Busca mais informações");
        buscaAvancada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaAvancada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscaAvancadaMouseClicked(evt);
            }
        });

        editarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-editar-usuário-masculino-30.png"))); // NOI18N
        editarCliente.setToolTipText("Editar Cliente");
        editarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarClienteMouseClicked(evt);
            }
        });

        deletarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-remover-usuário-masculino-30 (1).png"))); // NOI18N
        deletarCliente.setToolTipText("Remover Cliente");
        deletarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarClienteMouseClicked(evt);
            }
        });

        atulizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-atualizações-disponíveis-30.png"))); // NOI18N
        atulizar.setToolTipText("Atualizar");
        atulizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atulizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atulizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarClienteLayout = new javax.swing.GroupLayout(jPanelBuscarCliente);
        jPanelBuscarCliente.setLayout(jPanelBuscarClienteLayout);
        jPanelBuscarClienteLayout.setHorizontalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(novoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(buscaAvancada)
                        .addGap(18, 18, 18)
                        .addComponent(editarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(deletarCliente))
                    .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                                .addComponent(jButtonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atulizar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBuscarClienteLayout.setVerticalGroup(
            jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNome)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atulizar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscaAvancada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletarCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeActionPerformed
        String nome = firstToUpperCase(jTextFieldNome.getText());
        tableModel = JDBCCliente.listarClienteNome(nome);
        jTableCliente.setModel(tableModel);
    }//GEN-LAST:event_jButtonNomeActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked

    }//GEN-LAST:event_jTableClienteMouseClicked

    private void novoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoClienteMouseClicked
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_novoClienteMouseClicked

    private void buscaAvancadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaAvancadaMouseClicked
        int rowSelected = jTableCliente.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableCliente.getModel();
            int cd_cliente = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            tableModel = JDBCCliente.listarClienteAvancado(cd_cliente);
            jTableCliente.setModel(tableModel);
        } 
    }//GEN-LAST:event_buscaAvancadaMouseClicked

    private void editarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarClienteMouseClicked
        int rowSelected = jTableCliente.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um cliente!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableCliente.getModel();
            int cd_cliente = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            new AlterarCliente(cd_cliente).setVisible(true);
        }
    }//GEN-LAST:event_editarClienteMouseClicked

    private void deletarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarClienteMouseClicked
        int rowSelected = jTableCliente.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um funcionario!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableCliente.getModel();
            int cd_cliente = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            JDBCClienteDAO JDBCCliente = new JDBCClienteDAO();
            int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo deletar esse cliente?");
            if(opcao == 0) {
                if(JDBCCliente.deletarCliente(cd_cliente)) {
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO ao deletar!!");
                }
            }
        }
    }//GEN-LAST:event_deletarClienteMouseClicked

    private void atulizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atulizarMouseClicked
        tableModel = JDBCCliente.listarCliente();
        jTableCliente.setModel(tableModel);
    }//GEN-LAST:event_atulizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntidadeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntidadeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntidadeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntidadeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntidadeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atulizar;
    private javax.swing.JLabel buscaAvancada;
    private javax.swing.JLabel deletarCliente;
    private javax.swing.JLabel editarCliente;
    private javax.swing.JButton jButtonNome;
    private javax.swing.JPanel jPanelBuscarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel novoCliente;
    // End of variables declaration//GEN-END:variables
}
