/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui.entidade;

import br.com.ies.oficina.dao.jdbc.JDBCFuncionarioDAO;
import static br.com.ies.oficina.dominio.ManipuladorString.firstToUpperCase;
import br.com.ies.oficina.gui.alterar.AlterarFuncionario;
import br.com.ies.oficina.gui.cadastrar.CadastrarFuncionario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Weeaboo
 */
public class EntidadeFuncionario extends javax.swing.JFrame {
        JDBCFuncionarioDAO JDBCFuncionario = new JDBCFuncionarioDAO();
        TableModel tableModel;
        
    public EntidadeFuncionario() {
        initComponents();
        tableModel = JDBCFuncionario.listarFuncionario();
        jTableFuncionario.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        painelPrincipal = new javax.swing.JPanel();
        jButtonNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        jTextFieldNome = new javax.swing.JTextField();
        novoFunc = new javax.swing.JLabel();
        buscaAvancadaFunc = new javax.swing.JLabel();
        editarFunc = new javax.swing.JLabel();
        deletarFunc = new javax.swing.JLabel();
        atualizar = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Funcionario");

        painelPrincipal.setBackground(new java.awt.Color(32, 33, 35));
        painelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setPreferredSize(new java.awt.Dimension(600, 350));

        jButtonNome.setBackground(new java.awt.Color(46, 204, 113));
        jButtonNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jButtonNome.setForeground(new java.awt.Color(32, 33, 35));
        jButtonNome.setText("Buscar por nome");
        jButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeActionPerformed(evt);
            }
        });

        jTableFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jTableFuncionario.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        jTableFuncionario.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        jTableFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Título 4", "Título 5", "Título 6"
            }
        ));
        jScrollPane1.setViewportView(jTableFuncionario);

        jTextFieldNome.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNome.setForeground(new java.awt.Color(255, 255, 255));

        novoFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-adicionar-usuário-masculino-30.png"))); // NOI18N
        novoFunc.setToolTipText("Novo Funcionário");
        novoFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoFuncMouseClicked(evt);
            }
        });

        buscaAvancadaFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-procurar-usuário-masculino-30.png"))); // NOI18N
        buscaAvancadaFunc.setToolTipText("Buscar mais informações");
        buscaAvancadaFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaAvancadaFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscaAvancadaFuncMouseClicked(evt);
            }
        });

        editarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-editar-usuário-masculino-30.png"))); // NOI18N
        editarFunc.setToolTipText("Editar Funcionário");
        editarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarFuncMouseClicked(evt);
            }
        });

        deletarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-remover-usuário-masculino-30 (1).png"))); // NOI18N
        deletarFunc.setToolTipText("Remover Funcionário");
        deletarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletarFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarFuncMouseClicked(evt);
            }
        });

        atualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-atualizações-disponíveis-30.png"))); // NOI18N
        atualizar.setToolTipText("Atualizar");
        atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(novoFunc)
                        .addGap(18, 18, 18)
                        .addComponent(buscaAvancadaFunc)
                        .addGap(18, 18, 18)
                        .addComponent(editarFunc)
                        .addGap(18, 18, 18)
                        .addComponent(deletarFunc))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizar)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNome)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atualizar))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoFunc)
                    .addComponent(buscaAvancadaFunc)
                    .addComponent(editarFunc)
                    .addComponent(deletarFunc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void atualizarTabela(){
        tableModel = JDBCFuncionario.listarFuncionario();
        jTableFuncionario.setModel(tableModel);
    }
    
    private void jButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeActionPerformed
        String nome = firstToUpperCase(jTextFieldNome.getText());
        tableModel = JDBCFuncionario.listarFuncionarioNome(nome);
        jTableFuncionario.setModel(tableModel);
    }//GEN-LAST:event_jButtonNomeActionPerformed

    private void novoFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoFuncMouseClicked
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_novoFuncMouseClicked

    private void buscaAvancadaFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaAvancadaFuncMouseClicked
        int rowSelected = jTableFuncionario.getSelectedRow();
         if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um funcionario!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableFuncionario.getModel();
            int cd_funcionario = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            tableModel = JDBCFuncionario.listarFuncionarioAvancado(cd_funcionario);
            jTableFuncionario.setModel(tableModel);        
        }
    }//GEN-LAST:event_buscaAvancadaFuncMouseClicked

    private void editarFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarFuncMouseClicked
        int rowSelected = jTableFuncionario.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um funcionario!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableFuncionario.getModel();
            int cd_funcionario = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            new AlterarFuncionario(cd_funcionario).setVisible(true);          
        }    

    }//GEN-LAST:event_editarFuncMouseClicked

    private void deletarFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarFuncMouseClicked
        int rowSelected = jTableFuncionario.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um funcionario!");
        } else {
            DefaultTableModel model = (DefaultTableModel)jTableFuncionario.getModel();
            int cd_funcionario = Integer.parseInt((model.getValueAt(rowSelected, 0).toString()));
            JDBCFuncionarioDAO JDBCFuncionario = new JDBCFuncionarioDAO();
            int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo deletar esse funcionario?");
            if(opcao == 0) {
                if(JDBCFuncionario.deletarFuncionario(cd_funcionario)) {
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERRO ao deletar!!");
                }
            }
        }
    }//GEN-LAST:event_deletarFuncMouseClicked

    private void atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarMouseClicked
        tableModel = JDBCFuncionario.listarFuncionario();
        jTableFuncionario.setModel(tableModel);
    }//GEN-LAST:event_atualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntidadeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntidadeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntidadeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntidadeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntidadeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atualizar;
    private javax.swing.JLabel buscaAvancadaFunc;
    private javax.swing.JLabel deletarFunc;
    private javax.swing.JLabel editarFunc;
    private javax.swing.JButton jButtonNome;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel novoFunc;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
