/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui;


import java.awt.Color;

import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Herik
 */
public class MenuTeste extends javax.swing.JFrame {

    public MenuTeste() {
        initComponents();
        jPanelMenuInside.setVisible(true);
        jPanelOrcamento.setVisible(false);
        jPanelRelatorio.setVisible(false);
        jPanelGerenciar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuUpside = new javax.swing.JPanel();
        jLabelGerenciar3 = new javax.swing.JLabel();
        jPanelMenuRelatorio = new javax.swing.JPanel();
        jLabelGerenciarFuncionario3 = new javax.swing.JLabel();
        jPanelMenuGerenciar = new javax.swing.JPanel();
        jLabelGerenciarFuncionario1 = new javax.swing.JLabel();
        jPanelMenuOrcamento = new javax.swing.JPanel();
        jLabelGerenciarFuncionario2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelMenuInside = new javax.swing.JPanel();
        jPanelGerenciar = new javax.swing.JPanel();
        jPanelGerenciarVeiculo = new javax.swing.JPanel();
        jLabelGerenciarVeiculo = new javax.swing.JLabel();
        jLabelGerenciar = new javax.swing.JLabel();
        jPanelGerenciarFuncionario = new javax.swing.JPanel();
        jLabelGerenciarFuncionario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelGerenciarCliente = new javax.swing.JPanel();
        jLabelGerenciarCliente = new javax.swing.JLabel();
        jPanelGerenciarPeca = new javax.swing.JPanel();
        jLabelPeca = new javax.swing.JLabel();
        jPanelOrcamento = new javax.swing.JPanel();
        jLabelGerenciar1 = new javax.swing.JLabel();
        jPanelFuncionario1 = new javax.swing.JPanel();
        jLabelOrcamentoRealizar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelCliente1 = new javax.swing.JPanel();
        jLabelOrcamentoBuscar = new javax.swing.JLabel();
        jPanelRelatorio = new javax.swing.JPanel();
        jPanelRelatorioVeiculo = new javax.swing.JPanel();
        jLabelGerenciarVeiculo1 = new javax.swing.JLabel();
        jLabelGerenciar2 = new javax.swing.JLabel();
        jPanelFuncionario2 = new javax.swing.JPanel();
        jLabelRelatorioFuncionario = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelRelatorioCliente = new javax.swing.JPanel();
        jLabelGerenciarCliente1 = new javax.swing.JLabel();
        jPanelRelatorioPeca = new javax.swing.JPanel();
        jLabelPeca1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina Do Ricardão");

        jPanelMenuUpside.setBackground(new java.awt.Color(32, 33, 35));
        jPanelMenuUpside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGerenciar3.setBackground(new java.awt.Color(126, 87, 194));
        jLabelGerenciar3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciar3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciar3.setText("Menu");
        jPanelMenuUpside.add(jLabelGerenciar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanelMenuRelatorio.setBackground(new java.awt.Color(32, 33, 35));
        jPanelMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuRelatorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuRelatorioMouseEntered(evt);
            }
        });

        jLabelGerenciarFuncionario3.setBackground(new java.awt.Color(32, 33, 35));
        jLabelGerenciarFuncionario3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarFuncionario3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarFuncionario3.setText("Relatorio");

        javax.swing.GroupLayout jPanelMenuRelatorioLayout = new javax.swing.GroupLayout(jPanelMenuRelatorio);
        jPanelMenuRelatorio.setLayout(jPanelMenuRelatorioLayout);
        jPanelMenuRelatorioLayout.setHorizontalGroup(
            jPanelMenuRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuRelatorioLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelGerenciarFuncionario3)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelMenuRelatorioLayout.setVerticalGroup(
            jPanelMenuRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuRelatorioLayout.createSequentialGroup()
                .addComponent(jLabelGerenciarFuncionario3)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanelMenuUpside.add(jPanelMenuRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 30));

        jPanelMenuGerenciar.setBackground(new java.awt.Color(32, 33, 35));
        jPanelMenuGerenciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuGerenciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuGerenciarMouseEntered(evt);
            }
        });

        jLabelGerenciarFuncionario1.setBackground(new java.awt.Color(32, 33, 35));
        jLabelGerenciarFuncionario1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarFuncionario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarFuncionario1.setText("Gerenciar");
        jLabelGerenciarFuncionario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGerenciarFuncionario1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuGerenciarLayout = new javax.swing.GroupLayout(jPanelMenuGerenciar);
        jPanelMenuGerenciar.setLayout(jPanelMenuGerenciarLayout);
        jPanelMenuGerenciarLayout.setHorizontalGroup(
            jPanelMenuGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuGerenciarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabelGerenciarFuncionario1)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelMenuGerenciarLayout.setVerticalGroup(
            jPanelMenuGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuGerenciarLayout.createSequentialGroup()
                .addComponent(jLabelGerenciarFuncionario1)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanelMenuUpside.add(jPanelMenuGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 30));

        jPanelMenuOrcamento.setBackground(new java.awt.Color(32, 33, 35));
        jPanelMenuOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMenuOrcamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMenuOrcamentoMouseEntered(evt);
            }
        });

        jLabelGerenciarFuncionario2.setBackground(new java.awt.Color(32, 33, 35));
        jLabelGerenciarFuncionario2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarFuncionario2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarFuncionario2.setText("Orcamento");

        javax.swing.GroupLayout jPanelMenuOrcamentoLayout = new javax.swing.GroupLayout(jPanelMenuOrcamento);
        jPanelMenuOrcamento.setLayout(jPanelMenuOrcamentoLayout);
        jPanelMenuOrcamentoLayout.setHorizontalGroup(
            jPanelMenuOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOrcamentoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabelGerenciarFuncionario2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanelMenuOrcamentoLayout.setVerticalGroup(
            jPanelMenuOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuOrcamentoLayout.createSequentialGroup()
                .addComponent(jLabelGerenciarFuncionario2)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanelMenuUpside.add(jPanelMenuOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 30));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuInside.setBackground(new java.awt.Color(32, 33, 35));
        jPanelMenuInside.setForeground(new java.awt.Color(153, 0, 204));
        jPanelMenuInside.setPreferredSize(new java.awt.Dimension(250, 402));
        jPanelMenuInside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jPanelMenuInside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 270));

        jPanelGerenciar.setBackground(new java.awt.Color(32, 33, 35));
        jPanelGerenciar.setForeground(new java.awt.Color(153, 0, 204));
        jPanelGerenciar.setPreferredSize(new java.awt.Dimension(250, 402));
        jPanelGerenciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGerenciarVeiculo.setBackground(new java.awt.Color(32, 33, 35));
        jPanelGerenciarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGerenciarVeiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGerenciarVeiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGerenciarVeiculoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGerenciarVeiculoMousePressed(evt);
            }
        });

        jLabelGerenciarVeiculo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarVeiculo.setText("Veiculo");

        javax.swing.GroupLayout jPanelGerenciarVeiculoLayout = new javax.swing.GroupLayout(jPanelGerenciarVeiculo);
        jPanelGerenciarVeiculo.setLayout(jPanelGerenciarVeiculoLayout);
        jPanelGerenciarVeiculoLayout.setHorizontalGroup(
            jPanelGerenciarVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarVeiculoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabelGerenciarVeiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGerenciarVeiculoLayout.setVerticalGroup(
            jPanelGerenciarVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerenciarVeiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGerenciarVeiculo)
                .addContainerGap())
        );

        jPanelGerenciar.add(jPanelGerenciarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        jLabelGerenciar.setBackground(new java.awt.Color(126, 87, 194));
        jLabelGerenciar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciar.setText("Gerenciar");
        jPanelGerenciar.add(jLabelGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanelGerenciarFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jPanelGerenciarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelGerenciarFuncionarioMouseDragged(evt);
            }
        });
        jPanelGerenciarFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelGerenciarFuncionarioFocusGained(evt);
            }
        });
        jPanelGerenciarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGerenciarFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGerenciarFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGerenciarFuncionarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGerenciarFuncionarioMousePressed(evt);
            }
        });

        jLabelGerenciarFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jLabelGerenciarFuncionario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarFuncionario.setText("Funcionario");

        javax.swing.GroupLayout jPanelGerenciarFuncionarioLayout = new javax.swing.GroupLayout(jPanelGerenciarFuncionario);
        jPanelGerenciarFuncionario.setLayout(jPanelGerenciarFuncionarioLayout);
        jPanelGerenciarFuncionarioLayout.setHorizontalGroup(
            jPanelGerenciarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarFuncionarioLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabelGerenciarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGerenciarFuncionarioLayout.setVerticalGroup(
            jPanelGerenciarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGerenciarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGerenciar.add(jPanelGerenciarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelGerenciar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 130, 10));

        jPanelGerenciarCliente.setBackground(new java.awt.Color(32, 33, 35));
        jPanelGerenciarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGerenciarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGerenciarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGerenciarClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGerenciarClienteMousePressed(evt);
            }
        });

        jLabelGerenciarCliente.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarCliente.setText("Cliente");

        javax.swing.GroupLayout jPanelGerenciarClienteLayout = new javax.swing.GroupLayout(jPanelGerenciarCliente);
        jPanelGerenciarCliente.setLayout(jPanelGerenciarClienteLayout);
        jPanelGerenciarClienteLayout.setHorizontalGroup(
            jPanelGerenciarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarClienteLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelGerenciarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGerenciarClienteLayout.setVerticalGroup(
            jPanelGerenciarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerenciarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGerenciarCliente)
                .addGap(57, 57, 57))
        );

        jPanelGerenciar.add(jPanelGerenciarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 40));

        jPanelGerenciarPeca.setBackground(new java.awt.Color(32, 33, 35));
        jPanelGerenciarPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGerenciarPecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGerenciarPecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGerenciarPecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGerenciarPecaMousePressed(evt);
            }
        });

        jLabelPeca.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelPeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeca.setText("Peça");

        javax.swing.GroupLayout jPanelGerenciarPecaLayout = new javax.swing.GroupLayout(jPanelGerenciarPeca);
        jPanelGerenciarPeca.setLayout(jPanelGerenciarPecaLayout);
        jPanelGerenciarPecaLayout.setHorizontalGroup(
            jPanelGerenciarPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarPecaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabelPeca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGerenciarPecaLayout.setVerticalGroup(
            jPanelGerenciarPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerenciarPecaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPeca)
                .addContainerGap())
        );

        jPanelGerenciar.add(jPanelGerenciarPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 40));

        jLayeredPane1.add(jPanelGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 270));

        jPanelOrcamento.setBackground(new java.awt.Color(32, 33, 35));
        jPanelOrcamento.setForeground(new java.awt.Color(153, 0, 204));
        jPanelOrcamento.setPreferredSize(new java.awt.Dimension(250, 402));
        jPanelOrcamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGerenciar1.setBackground(new java.awt.Color(126, 87, 194));
        jLabelGerenciar1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciar1.setText("Orcamento");
        jPanelOrcamento.add(jLabelGerenciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanelFuncionario1.setBackground(new java.awt.Color(32, 33, 35));
        jPanelFuncionario1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelFuncionario1MouseDragged(evt);
            }
        });
        jPanelFuncionario1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelFuncionario1FocusGained(evt);
            }
        });
        jPanelFuncionario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFuncionario1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFuncionario1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFuncionario1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFuncionario1MousePressed(evt);
            }
        });

        jLabelOrcamentoRealizar.setBackground(new java.awt.Color(32, 33, 35));
        jLabelOrcamentoRealizar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelOrcamentoRealizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrcamentoRealizar.setText("Realizar");

        javax.swing.GroupLayout jPanelFuncionario1Layout = new javax.swing.GroupLayout(jPanelFuncionario1);
        jPanelFuncionario1.setLayout(jPanelFuncionario1Layout);
        jPanelFuncionario1Layout.setHorizontalGroup(
            jPanelFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionario1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabelOrcamentoRealizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFuncionario1Layout.setVerticalGroup(
            jPanelFuncionario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionario1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOrcamentoRealizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOrcamento.add(jPanelFuncionario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelOrcamento.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 130, 10));

        jPanelCliente1.setBackground(new java.awt.Color(32, 33, 35));
        jPanelCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCliente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCliente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCliente1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCliente1MousePressed(evt);
            }
        });

        jLabelOrcamentoBuscar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelOrcamentoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrcamentoBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanelCliente1Layout = new javax.swing.GroupLayout(jPanelCliente1);
        jPanelCliente1.setLayout(jPanelCliente1Layout);
        jPanelCliente1Layout.setHorizontalGroup(
            jPanelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCliente1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelOrcamentoBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCliente1Layout.setVerticalGroup(
            jPanelCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCliente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOrcamentoBuscar)
                .addGap(57, 57, 57))
        );

        jPanelOrcamento.add(jPanelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        jLayeredPane1.add(jPanelOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 270));

        jPanelRelatorio.setBackground(new java.awt.Color(32, 33, 35));
        jPanelRelatorio.setForeground(new java.awt.Color(153, 0, 204));
        jPanelRelatorio.setPreferredSize(new java.awt.Dimension(250, 402));
        jPanelRelatorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRelatorioVeiculo.setBackground(new java.awt.Color(32, 33, 35));
        jPanelRelatorioVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRelatorioVeiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatorioVeiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatorioVeiculoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRelatorioVeiculoMousePressed(evt);
            }
        });

        jLabelGerenciarVeiculo1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarVeiculo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarVeiculo1.setText("Veiculo");

        javax.swing.GroupLayout jPanelRelatorioVeiculoLayout = new javax.swing.GroupLayout(jPanelRelatorioVeiculo);
        jPanelRelatorioVeiculo.setLayout(jPanelRelatorioVeiculoLayout);
        jPanelRelatorioVeiculoLayout.setHorizontalGroup(
            jPanelRelatorioVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioVeiculoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabelGerenciarVeiculo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRelatorioVeiculoLayout.setVerticalGroup(
            jPanelRelatorioVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelatorioVeiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGerenciarVeiculo1)
                .addContainerGap())
        );

        jPanelRelatorio.add(jPanelRelatorioVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 40));

        jLabelGerenciar2.setBackground(new java.awt.Color(126, 87, 194));
        jLabelGerenciar2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciar2.setText("Relatorio");
        jPanelRelatorio.add(jLabelGerenciar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanelFuncionario2.setBackground(new java.awt.Color(32, 33, 35));
        jPanelFuncionario2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelFuncionario2MouseDragged(evt);
            }
        });
        jPanelFuncionario2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelFuncionario2FocusGained(evt);
            }
        });
        jPanelFuncionario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFuncionario2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFuncionario2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFuncionario2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFuncionario2MousePressed(evt);
            }
        });

        jLabelRelatorioFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jLabelRelatorioFuncionario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelRelatorioFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRelatorioFuncionario.setText("Funcionario");

        javax.swing.GroupLayout jPanelFuncionario2Layout = new javax.swing.GroupLayout(jPanelFuncionario2);
        jPanelFuncionario2.setLayout(jPanelFuncionario2Layout);
        jPanelFuncionario2Layout.setHorizontalGroup(
            jPanelFuncionario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionario2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabelRelatorioFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFuncionario2Layout.setVerticalGroup(
            jPanelFuncionario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelatorioFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRelatorio.add(jPanelFuncionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanelRelatorio.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 130, 10));

        jPanelRelatorioCliente.setBackground(new java.awt.Color(32, 33, 35));
        jPanelRelatorioCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRelatorioClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatorioClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatorioClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRelatorioClienteMousePressed(evt);
            }
        });

        jLabelGerenciarCliente1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelGerenciarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciarCliente1.setText("Cliente");

        javax.swing.GroupLayout jPanelRelatorioClienteLayout = new javax.swing.GroupLayout(jPanelRelatorioCliente);
        jPanelRelatorioCliente.setLayout(jPanelRelatorioClienteLayout);
        jPanelRelatorioClienteLayout.setHorizontalGroup(
            jPanelRelatorioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioClienteLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelGerenciarCliente1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRelatorioClienteLayout.setVerticalGroup(
            jPanelRelatorioClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelatorioClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGerenciarCliente1)
                .addGap(57, 57, 57))
        );

        jPanelRelatorio.add(jPanelRelatorioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        jPanelRelatorioPeca.setBackground(new java.awt.Color(32, 33, 35));
        jPanelRelatorioPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRelatorioPecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRelatorioPecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRelatorioPecaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRelatorioPecaMousePressed(evt);
            }
        });

        jLabelPeca1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabelPeca1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPeca1.setText("Peça");

        javax.swing.GroupLayout jPanelRelatorioPecaLayout = new javax.swing.GroupLayout(jPanelRelatorioPeca);
        jPanelRelatorioPeca.setLayout(jPanelRelatorioPecaLayout);
        jPanelRelatorioPecaLayout.setHorizontalGroup(
            jPanelRelatorioPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioPecaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabelPeca1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRelatorioPecaLayout.setVerticalGroup(
            jPanelRelatorioPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRelatorioPecaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPeca1)
                .addContainerGap())
        );

        jPanelRelatorio.add(jPanelRelatorioPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 40));

        jLayeredPane1.add(jPanelRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/backMenu.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMenuUpside, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenuUpside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGerenciarPecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarPecaMousePressed
        setColor(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarPecaMousePressed

    private void jPanelGerenciarPecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarPecaMouseExited
        resetColor(jPanelGerenciarPeca);
    }//GEN-LAST:event_jPanelGerenciarPecaMouseExited

    private void jPanelGerenciarPecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarPecaMouseEntered
        setColorEntered(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarPecaMouseEntered

    private void jPanelGerenciarPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarPecaMouseClicked

    }//GEN-LAST:event_jPanelGerenciarPecaMouseClicked

    private void jPanelGerenciarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarClienteMousePressed
        setColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarClienteMousePressed

    private void jPanelGerenciarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarClienteMouseExited
        resetColor(jPanelGerenciarCliente);
    }//GEN-LAST:event_jPanelGerenciarClienteMouseExited

    private void jPanelGerenciarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarClienteMouseEntered
        setColorEntered(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarClienteMouseEntered

    private void jPanelGerenciarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarClienteMouseClicked

    }//GEN-LAST:event_jPanelGerenciarClienteMouseClicked

    private void jPanelGerenciarFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioMousePressed
        setColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarFuncionarioMousePressed

    private void jPanelGerenciarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioMouseExited
        resetColor(jPanelGerenciarFuncionario);
    }//GEN-LAST:event_jPanelGerenciarFuncionarioMouseExited

    private void jPanelGerenciarFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioMouseEntered
        setColorEntered(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarPeca);
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarFuncionarioMouseEntered

    private void jPanelGerenciarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioMouseClicked

    }//GEN-LAST:event_jPanelGerenciarFuncionarioMouseClicked

    private void jPanelGerenciarFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioFocusGained

    }//GEN-LAST:event_jPanelGerenciarFuncionarioFocusGained

    private void jPanelGerenciarFuncionarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarFuncionarioMouseDragged

    }//GEN-LAST:event_jPanelGerenciarFuncionarioMouseDragged

    private void jPanelGerenciarVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarVeiculoMousePressed
        setColor(jPanelGerenciarVeiculo);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarPeca);
    }//GEN-LAST:event_jPanelGerenciarVeiculoMousePressed

    private void jPanelGerenciarVeiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarVeiculoMouseExited
        resetColor(jPanelGerenciarVeiculo);
    }//GEN-LAST:event_jPanelGerenciarVeiculoMouseExited

    private void jPanelGerenciarVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarVeiculoMouseEntered
        setColorEntered(jPanelGerenciarVeiculo);
        resetColor(jPanelGerenciarCliente);
        resetColor(jPanelGerenciarFuncionario);
        resetColor(jPanelGerenciarPeca);
    }//GEN-LAST:event_jPanelGerenciarVeiculoMouseEntered

    private void jPanelGerenciarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGerenciarVeiculoMouseClicked
        jPanelGerenciarVeiculo.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_jPanelGerenciarVeiculoMouseClicked

    private void jPanelFuncionario1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1MouseDragged

    private void jPanelFuncionario1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelFuncionario1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1FocusGained

    private void jPanelFuncionario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1MouseClicked

    private void jPanelFuncionario1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1MouseEntered

    private void jPanelFuncionario1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1MouseExited

    private void jPanelFuncionario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario1MousePressed

    private void jPanelCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCliente1MouseClicked

    private void jPanelCliente1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCliente1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCliente1MouseEntered

    private void jPanelCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCliente1MouseExited

    private void jPanelCliente1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCliente1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelCliente1MousePressed

    private void jPanelRelatorioVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioVeiculoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioVeiculoMouseClicked

    private void jPanelRelatorioVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioVeiculoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioVeiculoMouseEntered

    private void jPanelRelatorioVeiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioVeiculoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioVeiculoMouseExited

    private void jPanelRelatorioVeiculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioVeiculoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioVeiculoMousePressed

    private void jPanelFuncionario2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2MouseDragged

    private void jPanelFuncionario2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelFuncionario2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2FocusGained

    private void jPanelFuncionario2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2MouseClicked

    private void jPanelFuncionario2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2MouseEntered

    private void jPanelFuncionario2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2MouseExited

    private void jPanelFuncionario2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionario2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelFuncionario2MousePressed

    private void jPanelRelatorioClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioClienteMouseClicked

    private void jPanelRelatorioClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioClienteMouseEntered

    private void jPanelRelatorioClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioClienteMouseExited

    private void jPanelRelatorioClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioClienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioClienteMousePressed

    private void jPanelRelatorioPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioPecaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioPecaMouseClicked

    private void jPanelRelatorioPecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioPecaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioPecaMouseEntered

    private void jPanelRelatorioPecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioPecaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioPecaMouseExited

    private void jPanelRelatorioPecaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRelatorioPecaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelRelatorioPecaMousePressed

    private void jLabelGerenciarFuncionario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGerenciarFuncionario1MouseClicked

    }//GEN-LAST:event_jLabelGerenciarFuncionario1MouseClicked

    private void jPanelMenuOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuOrcamentoMouseClicked
        jPanelOrcamento.setVisible(true);
        jPanelGerenciar.setVisible(false);
        jPanelRelatorio.setVisible(false);
        jPanelMenuInside.setVisible(false);
    }//GEN-LAST:event_jPanelMenuOrcamentoMouseClicked

    private void jPanelMenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuRelatorioMouseClicked
        jPanelRelatorio.setVisible(true);
        jPanelOrcamento.setVisible(false);
        jPanelGerenciar.setVisible(false);
        jPanelMenuInside.setVisible(false);
    }//GEN-LAST:event_jPanelMenuRelatorioMouseClicked

    private void jPanelMenuGerenciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuGerenciarMouseClicked
        jPanelGerenciar.setVisible(true);
        jPanelOrcamento.setVisible(false);
        jPanelRelatorio.setVisible(false);
        jPanelMenuInside.setVisible(false);
    }//GEN-LAST:event_jPanelMenuGerenciarMouseClicked

    private void jPanelMenuGerenciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuGerenciarMouseEntered
        setColorMenu(jPanelMenuGerenciar);
        resetColorMenu(jPanelMenuOrcamento);
        resetColorMenu(jPanelMenuRelatorio);
    }//GEN-LAST:event_jPanelMenuGerenciarMouseEntered

    private void jPanelMenuOrcamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuOrcamentoMouseEntered
        setColorMenu(jPanelMenuOrcamento);
        resetColorMenu(jPanelMenuGerenciar);
        resetColorMenu(jPanelMenuRelatorio);
    }//GEN-LAST:event_jPanelMenuOrcamentoMouseEntered

    private void jPanelMenuRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuRelatorioMouseEntered
        setColorMenu(jPanelMenuRelatorio);
        resetColorMenu(jPanelMenuOrcamento);
        resetColorMenu(jPanelMenuGerenciar);
    }//GEN-LAST:event_jPanelMenuRelatorioMouseEntered
    void setColor(JPanel panel) {
        panel.setBackground(new Color(126,87,194));
    }
    
    void setColorEntered(JPanel panel) {
         panel.setBackground(new Color(126,87,194));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(32,33,35));
    }
    
    void setColorLabel(JLabel label) {
        label.setForeground(new Color(32,33,35));
    }
    
    void resetColorLabel(JLabel label) {
        label.setForeground(new Color(255,255,255));
    }
    
    void setColorMenu(JPanel panel) {
        panel.setBackground(new Color(126,87,194));
    }
    
    void resetColorMenu(JPanel panel) {
        panel.setBackground(new Color(32,33,35));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        new MenuTeste().setVisible(true);   
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGerenciar;
    private javax.swing.JLabel jLabelGerenciar1;
    private javax.swing.JLabel jLabelGerenciar2;
    private javax.swing.JLabel jLabelGerenciar3;
    private javax.swing.JLabel jLabelGerenciarCliente;
    private javax.swing.JLabel jLabelGerenciarCliente1;
    private javax.swing.JLabel jLabelGerenciarFuncionario;
    private javax.swing.JLabel jLabelGerenciarFuncionario1;
    private javax.swing.JLabel jLabelGerenciarFuncionario2;
    private javax.swing.JLabel jLabelGerenciarFuncionario3;
    private javax.swing.JLabel jLabelGerenciarVeiculo;
    private javax.swing.JLabel jLabelGerenciarVeiculo1;
    private javax.swing.JLabel jLabelOrcamentoBuscar;
    private javax.swing.JLabel jLabelOrcamentoRealizar;
    private javax.swing.JLabel jLabelPeca;
    private javax.swing.JLabel jLabelPeca1;
    private javax.swing.JLabel jLabelRelatorioFuncionario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCliente1;
    private javax.swing.JPanel jPanelFuncionario1;
    private javax.swing.JPanel jPanelFuncionario2;
    private javax.swing.JPanel jPanelGerenciar;
    private javax.swing.JPanel jPanelGerenciarCliente;
    private javax.swing.JPanel jPanelGerenciarFuncionario;
    private javax.swing.JPanel jPanelGerenciarPeca;
    private javax.swing.JPanel jPanelGerenciarVeiculo;
    private javax.swing.JPanel jPanelMenuGerenciar;
    private javax.swing.JPanel jPanelMenuInside;
    private javax.swing.JPanel jPanelMenuOrcamento;
    private javax.swing.JPanel jPanelMenuRelatorio;
    private javax.swing.JPanel jPanelMenuUpside;
    private javax.swing.JPanel jPanelOrcamento;
    private javax.swing.JPanel jPanelRelatorio;
    private javax.swing.JPanel jPanelRelatorioCliente;
    private javax.swing.JPanel jPanelRelatorioPeca;
    private javax.swing.JPanel jPanelRelatorioVeiculo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
