/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ies.oficina.gui.realizar;

import br.com.ies.oficina.dao.jdbc.JDBCClienteDAO;
import br.com.ies.oficina.dao.jdbc.JDBCFuncionarioDAO;
import br.com.ies.oficina.dao.jdbc.JDBCInventarioDAO;
import br.com.ies.oficina.dao.jdbc.JDBCOrdemServicoDAO;
import br.com.ies.oficina.dao.jdbc.JDBCVeiculoDAO;
import br.com.ies.oficina.dominio.Cliente;
import br.com.ies.oficina.dominio.Funcionario;
import br.com.ies.oficina.dominio.Inventario;
import static br.com.ies.oficina.dominio.ManipuladorString.contadorVazioCpf;
import static br.com.ies.oficina.dominio.ManipuladorString.contadorVazioPlaca;
import static br.com.ies.oficina.dominio.ManipuladorString.placaToUpperCase;
import static br.com.ies.oficina.dominio.ManipuladorString.verificarData;
import static br.com.ies.oficina.dominio.ManipuladorString.verificarHora;
import static br.com.ies.oficina.dominio.ManipuladorString.verificarInt;
import br.com.ies.oficina.dominio.OrdemServico;
import static br.com.ies.oficina.dominio.Pdf.gerarPdf;
import br.com.ies.oficina.dominio.Veiculo;
import br.com.ies.oficina.gui.entidade.EntidadeCliente;
import br.com.ies.oficina.gui.entidade.EntidadeFuncionario;
import br.com.ies.oficina.gui.entidade.EntidadeInventario;
import br.com.ies.oficina.gui.entidade.EntidadeVeiculo;
import java.awt.Cursor;
import java.text.DecimalFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;


/**
 *
 * @author Herik
 */
public class RealizarOrdemServico extends javax.swing.JFrame {
    JDBCClienteDAO JDBCCliente = new JDBCClienteDAO();
    JDBCVeiculoDAO JDBCVeiculo = new JDBCVeiculoDAO();
    JDBCInventarioDAO JDBCInventario = new JDBCInventarioDAO();
    JDBCFuncionarioDAO JDBCFuncionario = new JDBCFuncionarioDAO();
    
    Cursor cursor = new Cursor(HAND_CURSOR);
    Cliente cliente;
    Veiculo veiculo;
    Inventario inventario;
    Funcionario funcionario;
    
    int verificadorVazio;
    /**
     * Creates new form RealizarOrdemServico
     */
    public RealizarOrdemServico() {
        initComponents();
        //formattedMoney(jFormattedTextFieldMoney);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDadosCliente = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldNome.setEditable(false);
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldCidade.setEditable(false);
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabelTelefoneCliente = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jFormattedTextCpfCliente = new javax.swing.JFormattedTextField();
        jFormattedTextCpfCliente.setEditable(false);
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldBairro.setEditable(false);
        jLabelCidade = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelCpfCliente = new javax.swing.JLabel();
        jFormattedTextPreencherCpfCliente = new javax.swing.JFormattedTextField();
        searchCliente = new javax.swing.JLabel();
        buscarCliente = new javax.swing.JLabel();
        jPanelDadosVeiculo = new javax.swing.JPanel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldMarca.setEditable(false);
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldModelo.setEditable(false);
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldCor.setEditable(false);
        jFormattedTextPlacaVeiculo = new javax.swing.JFormattedTextField();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelMarcaVeiculo = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelPlacaVeiculo = new javax.swing.JLabel();
        jFormattedTextPlacaVeiculoEntrar = new javax.swing.JFormattedTextField();
        searchVeiculo = new javax.swing.JLabel();
        buscarVeiculo = new javax.swing.JLabel();
        jPanelDadosPeca = new javax.swing.JPanel();
        jTextFieldNomePeca = new javax.swing.JTextField();
        jTextFieldMarcaPeca = new javax.swing.JTextField();
        jTextFieldMarcaPeca.setEditable(false);
        jTextFieldDescricaoPeca = new javax.swing.JTextField();
        jTextFieldDescricaoPeca.setEditable(false);
        jTextFieldQuantidadePeca = new javax.swing.JTextField();
        jLabelNomePeca = new javax.swing.JLabel();
        jLabelMarcaPeca = new javax.swing.JLabel();
        jLabelDescricaoPeca = new javax.swing.JLabel();
        jLabelQuantidadePeca = new javax.swing.JLabel();
        jLabelPlacaVeiculo1 = new javax.swing.JLabel();
        jTextFieldCodigoPeca = new javax.swing.JTextField();
        searchPeca = new javax.swing.JLabel();
        buscarPeca = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jPanelDataHora = new javax.swing.JPanel();
        jLabelDataServico = new javax.swing.JLabel();
        jFormattedTextDataServico = new javax.swing.JFormattedTextField();
        jFormattedTextHoraServico = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        salvarPdf = new javax.swing.JLabel();
        imprimir = new javax.swing.JLabel();
        jPanelValorTotal = new javax.swing.JPanel();
        jLabelValorTotal = new javax.swing.JLabel();
        jLabelMoeda = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jPanelFuncionario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jTextFieldCdFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        searchFuncionario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buscarFuncionario = new javax.swing.JLabel();
        salvarBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar Ordem de Serviço");

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        jPanelDadosCliente.setBackground(new java.awt.Color(32, 33, 35));
        jPanelDadosCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));
        jPanelDadosCliente.setPreferredSize(new java.awt.Dimension(174, 162));

        jTextFieldNome.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNome.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldNome.setBorder(null);

        jTextFieldCidade.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldCidade.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldCidade.setBorder(null);

        jLabelNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeCliente.setText("Nome:");

        jLabelTelefoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefoneCliente.setText("Telefone:");

        jLabelCpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpf.setText("CPF:");

        jFormattedTextCpfCliente.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextCpfCliente.setBorder(null);
        jFormattedTextCpfCliente.setForeground(new java.awt.Color(46, 204, 113));
        try {
            jFormattedTextCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextFieldBairro.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldBairro.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldBairro.setBorder(null);

        jLabelCidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCidade.setText("Cidade:");

        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Bairro:");

        jTextFieldTelefone.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldTelefone.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldTelefone.setBorder(null);

        jLabelCpfCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpfCliente.setText("CPF do Cliente:");

        jFormattedTextPreencherCpfCliente.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextPreencherCpfCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jFormattedTextPreencherCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextPreencherCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextPreencherCpfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextPreencherCpfClienteFocusGained(evt);
            }
        });

        searchCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/searchIcon20px.png"))); // NOI18N
        searchCliente.setToolTipText("Buscar");
        searchCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchClienteMouseEntered(evt);
            }
        });

        buscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/buscarDados20.png"))); // NOI18N
        buscarCliente.setToolTipText("Ver lista");
        buscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarClienteMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosClienteLayout = new javax.swing.GroupLayout(jPanelDadosCliente);
        jPanelDadosCliente.setLayout(jPanelDadosClienteLayout);
        jPanelDadosClienteLayout.setHorizontalGroup(
            jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosClienteLayout.createSequentialGroup()
                        .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpf)
                            .addComponent(jLabelTelefoneCliente)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelBairro)
                            .addComponent(jLabelNomeCliente))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNome)
                            .addComponent(jTextFieldTelefone)
                            .addComponent(jFormattedTextCpfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldCidade)
                            .addComponent(jTextFieldBairro))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabelCpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextPreencherCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarCliente)
                        .addContainerGap())))
        );
        jPanelDadosClienteLayout.setVerticalGroup(
            jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextPreencherCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCpfCliente))
                    .addComponent(buscarCliente)
                    .addComponent(searchCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNomeCliente)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTelefoneCliente)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCpf)
                    .addComponent(jFormattedTextCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelDadosVeiculo.setBackground(new java.awt.Color(32, 33, 35));
        jPanelDadosVeiculo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jTextFieldMarca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldMarca.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldMarca.setBorder(null);

        jTextFieldModelo.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldModelo.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldModelo.setBorder(null);

        jTextFieldCor.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldCor.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldCor.setBorder(null);

        jFormattedTextPlacaVeiculo.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextPlacaVeiculo.setBorder(null);
        jFormattedTextPlacaVeiculo.setForeground(new java.awt.Color(46, 204, 113));
        try {
            jFormattedTextPlacaVeiculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextPlacaVeiculo.setEditable(false);

        jLabelPlaca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca.setText("Placa:");

        jLabelMarcaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcaVeiculo.setText("Marca:");

        jLabelModelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModelo.setText("Modelo:");

        jLabelCor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCor.setText("Cor:");

        jLabelPlacaVeiculo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPlacaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlacaVeiculo.setText("Placa do veiculo:");

        jFormattedTextPlacaVeiculoEntrar.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextPlacaVeiculoEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jFormattedTextPlacaVeiculoEntrar.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextPlacaVeiculoEntrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        searchVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/searchIcon20px.png"))); // NOI18N
        searchVeiculo.setToolTipText("Buscar");
        searchVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchVeiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchVeiculoMouseEntered(evt);
            }
        });

        buscarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/buscarDados20.png"))); // NOI18N
        buscarVeiculo.setToolTipText("Ver lista");
        buscarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarVeiculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarVeiculoMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosVeiculoLayout = new javax.swing.GroupLayout(jPanelDadosVeiculo);
        jPanelDadosVeiculo.setLayout(jPanelDadosVeiculoLayout);
        jPanelDadosVeiculoLayout.setHorizontalGroup(
            jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosVeiculoLayout.createSequentialGroup()
                        .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelMarcaVeiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                                .addComponent(jLabelModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jPanelDadosVeiculoLayout.createSequentialGroup()
                        .addComponent(jLabelPlacaVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextPlacaVeiculoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(searchVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarVeiculo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelDadosVeiculoLayout.setVerticalGroup(
            jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextPlacaVeiculoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPlacaVeiculo))
                    .addComponent(searchVeiculo)
                    .addComponent(buscarVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlaca))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarcaVeiculo))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModelo))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor))
                .addContainerGap())
        );

        jPanelDadosPeca.setBackground(new java.awt.Color(32, 33, 35));
        jPanelDadosPeca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jTextFieldNomePeca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNomePeca.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldNomePeca.setBorder(null);
        jTextFieldNomePeca.setEditable(false);

        jTextFieldMarcaPeca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldMarcaPeca.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldMarcaPeca.setBorder(null);

        jTextFieldDescricaoPeca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldDescricaoPeca.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldDescricaoPeca.setBorder(null);
        jTextFieldDescricaoPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoPecaActionPerformed(evt);
            }
        });

        jTextFieldQuantidadePeca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldQuantidadePeca.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldQuantidadePeca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelNomePeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomePeca.setText("Nome:");

        jLabelMarcaPeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcaPeca.setText("Marca");

        jLabelDescricaoPeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricaoPeca.setText("Descrição:");

        jLabelQuantidadePeca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuantidadePeca.setText("Quantidade:");

        jLabelPlacaVeiculo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPlacaVeiculo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlacaVeiculo1.setText("Codigo da peça:");

        jTextFieldCodigoPeca.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldCodigoPeca.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoPeca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        searchPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/searchIcon20px.png"))); // NOI18N
        searchPeca.setToolTipText("Buscar");
        searchPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchPecaMouseEntered(evt);
            }
        });

        buscarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/buscarDados20.png"))); // NOI18N
        buscarPeca.setToolTipText("Ver lista");
        buscarPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarPecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarPecaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelDadosPecaLayout = new javax.swing.GroupLayout(jPanelDadosPeca);
        jPanelDadosPeca.setLayout(jPanelDadosPecaLayout);
        jPanelDadosPecaLayout.setHorizontalGroup(
            jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPecaLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomePeca)
                            .addComponent(jLabelMarcaPeca)
                            .addComponent(jLabelDescricaoPeca)
                            .addComponent(jLabelQuantidadePeca))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMarcaPeca)
                            .addComponent(jTextFieldDescricaoPeca)
                            .addComponent(jTextFieldQuantidadePeca)
                            .addComponent(jTextFieldNomePeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosPecaLayout.createSequentialGroup()
                        .addComponent(jLabelPlacaVeiculo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarPeca)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelDadosPecaLayout.setVerticalGroup(
            jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPlacaVeiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPeca)
                    .addComponent(buscarPeca)
                    .addComponent(jTextFieldCodigoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomePeca))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarcaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarcaPeca))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricaoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescricaoPeca))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadePeca))
                .addContainerGap())
        );

        jPanelDescricao.setBackground(new java.awt.Color(32, 33, 35));
        jPanelDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição do serviço:");

        jTextAreaDescricao.setBackground(new java.awt.Color(32, 33, 35));
        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout jPanelDescricaoLayout = new javax.swing.GroupLayout(jPanelDescricao);
        jPanelDescricao.setLayout(jPanelDescricaoLayout);
        jPanelDescricaoLayout.setHorizontalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18))
        );
        jPanelDescricaoLayout.setVerticalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );

        jPanelDataHora.setBackground(new java.awt.Color(32, 33, 35));
        jPanelDataHora.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jLabelDataServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataServico.setText("Data:");

        jFormattedTextDataServico.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextDataServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jFormattedTextDataServico.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextDataServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextHoraServico.setBackground(new java.awt.Color(32, 33, 35));
        jFormattedTextHoraServico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jFormattedTextHoraServico.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextHoraServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hora:");

        javax.swing.GroupLayout jPanelDataHoraLayout = new javax.swing.GroupLayout(jPanelDataHora);
        jPanelDataHora.setLayout(jPanelDataHoraLayout);
        jPanelDataHoraLayout.setHorizontalGroup(
            jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataServico)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextHoraServico)
                    .addComponent(jFormattedTextDataServico, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDataHoraLayout.setVerticalGroup(
            jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDataServico)
                    .addComponent(jFormattedTextDataServico, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextHoraServico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salvarPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-pdf30.png"))); // NOI18N
        salvarPdf.setToolTipText("Gerar PDF");
        salvarPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarPdfMouseClicked(evt);
            }
        });

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-impressão-30.png"))); // NOI18N
        imprimir.setToolTipText("Imprimir");

        jPanelValorTotal.setBackground(new java.awt.Color(32, 33, 35));
        jPanelValorTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jLabelValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorTotal.setText("Valor total:");

        jLabelMoeda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMoeda.setText("R$");

        jTextFieldValorTotal.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldValorTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout jPanelValorTotalLayout = new javax.swing.GroupLayout(jPanelValorTotal);
        jPanelValorTotal.setLayout(jPanelValorTotalLayout);
        jPanelValorTotalLayout.setHorizontalGroup(
            jPanelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelValorTotalLayout.createSequentialGroup()
                        .addComponent(jLabelValorTotal)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(jPanelValorTotalLayout.createSequentialGroup()
                        .addComponent(jLabelMoeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorTotal)))
                .addContainerGap())
        );
        jPanelValorTotalLayout.setVerticalGroup(
            jPanelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoeda)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jPanelFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 60), 3, true));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionario:");

        jTextFieldNomeFuncionario.setEditable(false);
        jTextFieldNomeFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldNomeFuncionario.setForeground(new java.awt.Color(46, 204, 113));
        jTextFieldNomeFuncionario.setBorder(null);

        jTextFieldCdFuncionario.setBackground(new java.awt.Color(32, 33, 35));
        jTextFieldCdFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCdFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo:");

        searchFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/searchIcon20px.png"))); // NOI18N
        searchFuncionario.setToolTipText("Buscar");
        searchFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFuncionarioMouseClicked(evt);
            }
        });

        buscarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/buscarDados20.png"))); // NOI18N
        buscarFuncionario.setToolTipText("Ver lista");
        buscarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarFuncionarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFuncionarioLayout = new javax.swing.GroupLayout(jPanelFuncionario);
        jPanelFuncionario.setLayout(jPanelFuncionarioLayout);
        jPanelFuncionarioLayout.setHorizontalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFuncionarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createSequentialGroup()
                        .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCdFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarFuncionario)
                        .addGap(23, 23, 23))))
        );
        jPanelFuncionarioLayout.setVerticalGroup(
            jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldCdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        salvarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ies/oficina/pics/icons8-salvar-30.png"))); // NOI18N
        salvarBanco.setToolTipText("Salvar");
        salvarBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarBancoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDataHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarBanco)
                        .addGap(39, 39, 39)
                        .addComponent(salvarPdf)
                        .addGap(38, 38, 38)
                        .addComponent(imprimir)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelDadosVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(jPanelDadosPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDadosVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jPanelDadosPeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imprimir)
                    .addComponent(jPanelDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(salvarBanco)
                        .addComponent(salvarPdf)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        /*public void formattedMoney(JFormattedTextField jFormattedTextFieldMoney) {
            DecimalFormat decimal = new DecimalFormat("#,###,###.00");
            NumberFormatter numFormatter = new NumberFormatter(decimal);
            numFormatter.setFormat(decimal);
            numFormatter.setAllowsInvalid(false);
            DefaultFormatterFactory dfFactory = new DefaultFormatterFactory(numFormatter);
         
            jFormattedTextFieldMoney.setFormatterFactory(dfFactory);
        }*/
    
    private void searchClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchClienteMouseEntered
        searchCliente.setCursor(cursor);
    }//GEN-LAST:event_searchClienteMouseEntered

    private void searchVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchVeiculoMouseEntered
        searchVeiculo.setCursor(cursor);
    }//GEN-LAST:event_searchVeiculoMouseEntered

    private void searchPecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPecaMouseEntered
        searchPeca.setCursor(cursor);
    }//GEN-LAST:event_searchPecaMouseEntered

    private void searchClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchClienteMouseClicked
        verificadorVazio = contadorVazioCpf(jFormattedTextPreencherCpfCliente.getText());
        
        if(verificadorVazio == 0) {
            int codigo = JDBCCliente.buscarCodigo(jFormattedTextPreencherCpfCliente.getText());
            cliente = JDBCCliente.buscarClienteDadosPessoais(codigo);

            jTextFieldNome.setText(cliente.getNome());
            jTextFieldTelefone.setText(cliente.getTelefone());
            jFormattedTextCpfCliente.setText(cliente.getCpf());
            jTextFieldCidade.setText(cliente.getCidade());
            jTextFieldBairro.setText(cliente.getBairro());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe o CPF!");
        }
        
    }//GEN-LAST:event_searchClienteMouseClicked

    private void searchVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchVeiculoMouseClicked
        verificadorVazio = contadorVazioPlaca(jFormattedTextPlacaVeiculoEntrar.getText()); 
        
        if(verificadorVazio == 0) {
           int codigo = JDBCVeiculo.buscarCodigo(placaToUpperCase(jFormattedTextPlacaVeiculoEntrar.getText()));
           veiculo = JDBCVeiculo.buscarVeiculoDados(codigo);

           jFormattedTextPlacaVeiculo.setText(veiculo.getPlaca());
           jTextFieldMarca.setText(veiculo.getMarca());
           jTextFieldModelo.setText(veiculo.getModelo());
        jTextFieldCor.setText(veiculo.getCor());       
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe a placa!");
        }

    }//GEN-LAST:event_searchVeiculoMouseClicked

    private void buscarPecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarPecaMouseEntered
        buscarPeca.setCursor(cursor);
    }//GEN-LAST:event_buscarPecaMouseEntered

    private void buscarPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarPecaMouseClicked
        new EntidadeInventario().setVisible(true);
    }//GEN-LAST:event_buscarPecaMouseClicked

    private void buscarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarVeiculoMouseClicked
        new EntidadeVeiculo().setVisible(true);
    }//GEN-LAST:event_buscarVeiculoMouseClicked

    private void buscarVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarVeiculoMouseEntered
        buscarVeiculo.setCursor(cursor);
    }//GEN-LAST:event_buscarVeiculoMouseEntered

    private void buscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarClienteMouseClicked
        new EntidadeCliente().setVisible(true);
    }//GEN-LAST:event_buscarClienteMouseClicked

    private void buscarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarClienteMouseEntered
        buscarCliente.setCursor(cursor);
    }//GEN-LAST:event_buscarClienteMouseEntered

    private void searchPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPecaMouseClicked
        if(verificarInt(jTextFieldCodigoPeca.getText())) {
            inventario = JDBCInventario.buscarInventario(Integer.parseInt(jTextFieldCodigoPeca.getText()));

            jTextFieldNomePeca.setText(inventario.getNome());
            jTextFieldMarcaPeca.setText(inventario.getMarca());
            jTextFieldDescricaoPeca.setText(inventario.getDescricao());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe um numero!");
        }
               
    }//GEN-LAST:event_searchPecaMouseClicked

    private void jTextFieldDescricaoPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoPecaActionPerformed

    private void jFormattedTextPreencherCpfClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextPreencherCpfClienteFocusGained

    }//GEN-LAST:event_jFormattedTextPreencherCpfClienteFocusGained

    private void salvarPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarPdfMouseClicked
        try {
            if(verificarInt(jTextFieldQuantidadePeca.getText()) == false) {
                JOptionPane.showMessageDialog(rootPane, "Informe uma quantidade de peça valida!");
            }
            String data = jFormattedTextDataServico.getText();
                if(verificarData(data) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Data incorreta!");
                }
            String hora = jFormattedTextHoraServico.getText();
                if(verificarHora(hora) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Horario incorreto!");
                 }
            String descricao = jTextAreaDescricao.getText();
                if(verificarInt(jTextFieldValorTotal.getText()) == false) {
                     JOptionPane.showMessageDialog(rootPane, "Informe um valor da OS valido!!");
                }
            Cliente cliente = new Cliente(jTextFieldNome.getText(),jFormattedTextCpfCliente.getText(), null, null, jTextFieldTelefone.getText(), jTextFieldCidade.getText(), jTextFieldBairro.getText(), null, null, null, null);
            Funcionario funcionario = new Funcionario(jTextFieldNomeFuncionario.getText(), null, null, null, null, null, null, null, null, null, null);
            funcionario.setCd_funcionario(Integer.parseInt(jTextFieldCdFuncionario.getText()));
            Veiculo veiculo = new Veiculo(jTextFieldMarca.getText(),jTextFieldCor.getText(),jTextFieldModelo.getText(),jFormattedTextPlacaVeiculo.getText());
            Inventario inventario = new Inventario(jTextFieldMarcaPeca.getText(), Integer.parseInt(jTextFieldQuantidadePeca.getText()), jTextFieldNomePeca.getText(), jTextFieldDescricaoPeca.getText());
            inventario.setCd_inventario(Integer.parseInt(jTextFieldCodigoPeca.getText()));                
            int valorTotal = Integer.parseInt(jTextFieldValorTotal.getText());
            OrdemServico ordemServico = new OrdemServico(cliente, veiculo ,inventario, funcionario, data, hora ,valorTotal, descricao);
            gerarPdf(ordemServico);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        }

    }//GEN-LAST:event_salvarPdfMouseClicked

    private void buscarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarFuncionarioMouseClicked
        new EntidadeFuncionario().setVisible(true);
    }//GEN-LAST:event_buscarFuncionarioMouseClicked

    private void searchFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFuncionarioMouseClicked
        if(verificarInt(jTextFieldCdFuncionario.getText())) {
            funcionario = JDBCFuncionario.buscarFuncionarioDadosPessoais(Integer.parseInt(jTextFieldCdFuncionario.getText()));

            jTextFieldNomeFuncionario.setText(funcionario.getNome());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe um numero!");
        }
    }//GEN-LAST:event_searchFuncionarioMouseClicked

    private void salvarBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarBancoMouseClicked
        try {
            if(verificarInt(jTextFieldQuantidadePeca.getText()) == false) {
                JOptionPane.showMessageDialog(rootPane, "Informe uma quantidade de peça valida!");
            }
            String data = jFormattedTextDataServico.getText();
                if(verificarData(data) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Data incorreta!");
                }
            String hora = jFormattedTextHoraServico.getText();
                if(verificarHora(hora) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Horario incorreto!");
                 }
            String descricao = jTextAreaDescricao.getText();
                if(verificarInt(jTextFieldValorTotal.getText()) == false) {
                     JOptionPane.showMessageDialog(rootPane, "Informe um valor da OS valido!!");
                }
            Cliente cliente = new Cliente(jTextFieldNome.getText(),jFormattedTextCpfCliente.getText(), null, null, jTextFieldTelefone.getText(), jTextFieldCidade.getText(), jTextFieldBairro.getText(), null, null, null, null);
            Funcionario funcionario = new Funcionario(jTextFieldNomeFuncionario.getText(), null, null, null, null, null, null, null, null, null, null);
            funcionario.setCd_funcionario(Integer.parseInt(jTextFieldCdFuncionario.getText()));
            Veiculo veiculo = new Veiculo(jTextFieldMarca.getText(),jTextFieldCor.getText(),jTextFieldModelo.getText(),jFormattedTextPlacaVeiculo.getText());
            Inventario inventario = new Inventario(jTextFieldMarcaPeca.getText(), Integer.parseInt(jTextFieldQuantidadePeca.getText()), jTextFieldNomePeca.getText(), jTextFieldDescricaoPeca.getText());
            inventario.setCd_inventario(Integer.parseInt(jTextFieldCodigoPeca.getText()));                
            String valorTotalString = jTextFieldValorTotal.getText();
            int valorTotal = Integer.parseInt(valorTotalString);
            OrdemServico ordemServico = new OrdemServico(cliente, veiculo ,inventario, funcionario, data, hora ,valorTotal, descricao);
            
            JDBCOrdemServicoDAO JDBCOrdemServico = new JDBCOrdemServicoDAO();
                if(JDBCOrdemServico.salvarOrdemServico(ordemServico)) {
                    JOptionPane.showMessageDialog(rootPane, "Salvado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao salvar!");
                }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_salvarBancoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarOrdemServico().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarCliente;
    private javax.swing.JLabel buscarFuncionario;
    private javax.swing.JLabel buscarPeca;
    private javax.swing.JLabel buscarVeiculo;
    private javax.swing.JLabel imprimir;
    private javax.swing.JFormattedTextField jFormattedTextCpfCliente;
    private javax.swing.JFormattedTextField jFormattedTextDataServico;
    private javax.swing.JFormattedTextField jFormattedTextHoraServico;
    private javax.swing.JFormattedTextField jFormattedTextPlacaVeiculo;
    private javax.swing.JFormattedTextField jFormattedTextPlacaVeiculoEntrar;
    private javax.swing.JFormattedTextField jFormattedTextPreencherCpfCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelCpfCliente;
    private javax.swing.JLabel jLabelDataServico;
    private javax.swing.JLabel jLabelDescricaoPeca;
    private javax.swing.JLabel jLabelMarcaPeca;
    private javax.swing.JLabel jLabelMarcaVeiculo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMoeda;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNomePeca;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlacaVeiculo;
    private javax.swing.JLabel jLabelPlacaVeiculo1;
    private javax.swing.JLabel jLabelQuantidadePeca;
    private javax.swing.JLabel jLabelTelefoneCliente;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDadosCliente;
    private javax.swing.JPanel jPanelDadosPeca;
    private javax.swing.JPanel jPanelDadosVeiculo;
    private javax.swing.JPanel jPanelDataHora;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelFuncionario;
    private javax.swing.JPanel jPanelValorTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCdFuncionario;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigoPeca;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldDescricaoPeca;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMarcaPeca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldNomePeca;
    private javax.swing.JTextField jTextFieldQuantidadePeca;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JLabel salvarBanco;
    private javax.swing.JLabel salvarPdf;
    private javax.swing.JLabel searchCliente;
    private javax.swing.JLabel searchFuncionario;
    private javax.swing.JLabel searchPeca;
    private javax.swing.JLabel searchVeiculo;
    // End of variables declaration//GEN-END:variables
}
